schema_version = "1.0.0"

id = "rig_weaver"
version = "0.1.0"
name = "RigWeaver"
tagline = "Bone extraction and simulation proxy mesh tools"
maintainer = "theweapon"
type = "add-on"

blender_version_min = "4.5.0"

license = ["SPDX:GPL-3.0-or-later"]

tags = ["Rigging", "Armature"]
